// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Common environment lifecycle phases.
 */
export type EnvironmentPhase = "unknown" | "creating" | "starting" | "running" | "updating" | "stopping" | "stopped" | "deleting" | "deleted";
