// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Structured source used to provision a dynamic environment.
 */
export type EnvironmentSource = { repositoryUrl: string,
/**
 * Opaque provider-interpreted Git ref.
 */
ref: string, };
