// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Authentication supplied when creating or updating an environment provider.
 */
export type EnvironmentProviderAuthenticationParams = { "type": "pat", token: string, };
