// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Provider-qualified identity of an environment.
 */
export type EnvironmentRef = { providerId: string, environmentId: string, };
