// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvironmentProviderAuthentication } from "./EnvironmentProviderAuthentication";
import type { EnvironmentProviderKind } from "./EnvironmentProviderKind";

/**
 * An environment provider visible through the app-server API.
 */
export type EnvironmentProvider = { id: string, name: string, kind: EnvironmentProviderKind,
/**
 * Resolved control-plane URL, or `null` for the built-in static provider.
 */
url: string | null,
/**
 * Redacted authentication metadata, or `null` for the built-in static provider.
 */
authentication: EnvironmentProviderAuthentication | null, };
