// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvironmentRef } from "./EnvironmentRef";
import type { EnvironmentSource } from "./EnvironmentSource";
import type { EnvironmentStatus } from "./EnvironmentStatus";

/**
 * An environment visible through the app-server API.
 */
export type Environment = { ref: EnvironmentRef,
/**
 * Provisioning source, or `null` for a statically registered environment.
 */
source: EnvironmentSource | null,
/**
 * Provider-native size or machine class, or `null` for a static environment.
 */
resourceClass: string | null, status: EnvironmentStatus, };
