// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvironmentPhase } from "./EnvironmentPhase";

/**
 * Current environment lifecycle status.
 */
export type EnvironmentStatus = { phase: EnvironmentPhase, error: string | null, };
